-- Auto-generated by scripts/geocode_pois.py
-- Geocoded via Google Maps (Playwright)

UPDATE public.pois SET lat = 55.6837848, lng = 12.568928 WHERE id = '2720fc84-f690-5b93-bff8-dc4883cda4e1'; -- Torvehallerne
UPDATE public.pois SET lat = 55.6936333, lng = 12.6082318 WHERE id = '60a0c640-12e7-51bf-8d45-237839acb69f'; -- Reffen Street Food
UPDATE public.pois SET lat = 55.6798752, lng = 12.5733676 WHERE id = 'b35796d8-a452-5176-a7bb-8b06526b6936'; -- Paludan Bog & Café
UPDATE public.pois SET lat = 55.7061815, lng = 12.5818152 WHERE id = 'e4076f99-c3d1-53d6-b1ab-d81d02343a69'; -- Juno the Bakery
UPDATE public.pois SET lat = 55.6685024, lng = 12.5599359 WHERE id = '9b905bdb-3ad4-53e4-af78-11eee702bbed'; -- Warpigs
UPDATE public.pois SET lat = 55.6778772, lng = 12.5968088 WHERE id = '08d3d318-aa0e-560e-b04e-2876ec4aecf2'; -- Broens Gadekøkken
UPDATE public.pois SET lat = 55.6923117, lng = 12.5560779 WHERE id = 'ecc49c62-7c34-5ad0-9754-d21fcc31f16a'; -- Bæst
UPDATE public.pois SET lat = 55.6656681, lng = 12.5496042 WHERE id = '871a1350-c84d-5460-9da4-5e9058d51351'; -- Café Dyrehaven
UPDATE public.pois SET lat = 55.6833518, lng = 12.5661528 WHERE id = '5d821002-597f-5672-8162-4a0ead97c687'; -- Høst
UPDATE public.pois SET lat = 55.691235, lng = 12.5592894 WHERE id = '17696b38-b3dd-537a-b967-5c5635969778'; -- Rust
UPDATE public.pois SET lat = 55.6681108, lng = 12.5438031 WHERE id = 'f07f4dfa-82a1-587d-8135-84882e58597c'; -- VEGA
UPDATE public.pois SET lat = 55.6863855, lng = 12.5839928 WHERE id = '37e496c1-7579-5490-a23e-d9f8f49888ce'; -- Culture Box
UPDATE public.pois SET lat = 55.6921531, lng = 12.5561452 WHERE id = '575fea65-1138-560d-b6f3-9c1519536293'; -- BRUS
UPDATE public.pois SET lat = 55.6728044, lng = 12.5516122 WHERE id = '13b22126-f096-5146-aa30-a7f32f991fb7'; -- Lidkoeb
UPDATE public.pois SET lat = 55.6800628, lng = 12.5758287 WHERE id = '038d42c6-48a6-5189-9b3f-a177148c2cd8'; -- The Jane
UPDATE public.pois SET lat = 55.6901306, lng = 12.5637778 WHERE id = '1f7bce4f-ff19-50bc-aefe-50db829dcc01'; -- Nørrebro Bryghus
UPDATE public.pois SET lat = 55.7746853, lng = 12.5772659 WHERE id = '5d6ebd8a-d293-5bea-863e-08a078fdb687'; -- Bakken
UPDATE public.pois SET lat = 55.6773697, lng = 12.5816522 WHERE id = '484bf1f1-57f1-5867-9c43-7ba0c902a1da'; -- Ved Stranden 10
UPDATE public.pois SET lat = 55.6673056, lng = 12.5612166 WHERE id = '4dd38765-6d58-5f57-b45c-498500683f96'; -- Jolene Bar
UPDATE public.pois SET lat = 55.6889055, lng = 12.5597384 WHERE id = 'd40071fd-315c-5215-be97-b6b2b04f8df7'; -- Gefährlich
UPDATE public.pois SET lat = 55.6659836, lng = 12.5588521 WHERE id = '56dc62fb-d2c6-5c00-8ff1-c5b4bd648dbf'; -- KB18
UPDATE public.pois SET lat = 55.6888127, lng = 12.5783303 WHERE id = 'f68be660-7e44-5a66-96dd-894afa177a09'; -- SMK – National Gallery of Denmark
UPDATE public.pois SET lat = 55.67298, lng = 12.572543 WHERE id = 'b9e3fb03-739f-5000-9cd0-9679dc3e843f'; -- Ny Carlsberg Glyptotek
UPDATE public.pois SET lat = 55.6858274, lng = 12.5772687 WHERE id = '7de7e799-5bf4-5e11-b7a3-041876802823'; -- Rosenborg Castle
UPDATE public.pois SET lat = 55.681347, lng = 12.5757299 WHERE id = 'ab532da9-e475-5ba4-9919-4aacc86d1a87'; -- The Round Tower
UPDATE public.pois SET lat = 55.6797676, lng = 12.5907984 WHERE id = '263b478c-3151-5232-a695-ed86abb74f20'; -- Nyhavn
UPDATE public.pois SET lat = 55.677963, lng = 12.6051861 WHERE id = '6f93f603-864b-552e-aba4-7f3769d6cde2'; -- Freetown Christiania
UPDATE public.pois SET lat = 55.6821758, lng = 12.6000932 WHERE id = '578618c5-2d37-5665-9efd-8adb87c41c0d'; -- Copenhagen Opera House
UPDATE public.pois SET lat = 55.6865563, lng = 12.5928423 WHERE id = '12745095-b655-5973-98d5-fcd0ff205106'; -- Designmuseum Danmark
UPDATE public.pois SET lat = 55.6874652, lng = 12.5767806 WHERE id = '1bf00cf6-e6d6-5ec0-a90f-997b099e0f1b'; -- Natural History Museum of Denmark
UPDATE public.pois SET lat = 55.6910102, lng = 12.5501532 WHERE id = 'ee1d1659-edcf-5889-b45b-239a2d3c74fb'; -- Assistens Cemetery
UPDATE public.pois SET lat = 55.6849043, lng = 12.5733926 WHERE id = 'ef5963d1-117a-52ef-a888-301cf4f47741'; -- Botanical Garden Copenhagen
UPDATE public.pois SET lat = 55.6840588, lng = 12.5930201 WHERE id = 'c0a00f38-d3b1-5004-b92d-16567a068159'; -- Amalienborg Palace
UPDATE public.pois SET lat = 55.6733994, lng = 12.5826588 WHERE id = '0544ad93-87aa-54a5-86d0-4949793eb3ff'; -- The Black Diamond
UPDATE public.pois SET lat = 55.6729387, lng = 12.5942102 WHERE id = 'fe4f84f5-0ce6-51f5-9566-b6d7e0acadc6'; -- Church of Our Saviour
UPDATE public.pois SET lat = 55.6695374, lng = 12.5242031 WHERE id = '1847631d-318a-5210-b367-68a2e8ad6505'; -- Cisternerne
UPDATE public.pois SET lat = 55.6809067, lng = 12.5736671 WHERE id = 'd20cddb1-c03d-5737-a180-b2ee63abd1b2'; -- Copenhagen Central Library
UPDATE public.pois SET lat = 55.6811862, lng = 12.5762561 WHERE id = 'effbceab-04c0-5d27-9ea5-9f502bd92d26'; -- Studenterhuset
UPDATE public.pois SET lat = 55.6675548, lng = 12.5482188 WHERE id = '661ebac4-1fc9-5412-8616-1fd9233376c6'; -- Riccos Kaffebar Istedgade
UPDATE public.pois SET lat = 55.6724602, lng = 12.5791827 WHERE id = 'ea944ac5-8917-5ee5-a617-97aeac73fd05'; -- BLOX Café
UPDATE public.pois SET lat = 55.6789112, lng = 12.5799328 WHERE id = '97b0544d-9dd6-5b30-8e49-b4ea703e736e'; -- Café Norden
UPDATE public.pois SET lat = 55.6810135, lng = 12.5669485 WHERE id = 'c9e2c754-3d5e-5910-9b89-87077f9dade0'; -- Ørstedsparken
UPDATE public.pois SET lat = 55.6748106, lng = 12.5254766 WHERE id = '1f9f3990-20ae-52d3-923f-70403b70ea49'; -- Frederiksberg Have
UPDATE public.pois SET lat = 55.6788341, lng = 12.5742518 WHERE id = '008179de-5535-5f38-8b0c-375195944af8'; -- Jorcks Passage
UPDATE public.pois SET lat = 55.7013424, lng = 12.5426383 WHERE id = 'c338757e-5b17-5fb9-b3b7-f9e12ae113e7'; -- Superkilen
UPDATE public.pois SET lat = 55.691376, lng = 12.594301 WHERE id = 'dacadbe0-c321-5e99-aa80-0455622e0291'; -- Kastellet
UPDATE public.pois SET lat = 55.6545325, lng = 12.6496067 WHERE id = '4ccd7af5-3896-5f54-a402-dd41d0537ae7'; -- Amager Strandpark
UPDATE public.pois SET lat = 55.6866466, lng = 12.5573308 WHERE id = 'ab9fb68c-0206-53d2-978f-75544f10c661'; -- Blågårds Plads
UPDATE public.pois SET lat = 55.6955245, lng = 12.6093316 WHERE id = 'ef3b8e33-5926-584e-aa2e-c18e5e1a3730'; -- Halvandet
UPDATE public.pois SET lat = 55.6791439, lng = 12.5689981 WHERE id = '7b16e8c0-f567-5dba-8f2b-df34200064c7'; -- Sankt Peders Stræde
UPDATE public.pois SET lat = 55.6824324, lng = 12.5963819 WHERE id = '3f8db6f2-fdbe-5662-873c-0382cf50baae'; -- Ofelia Beach
